### ISSUE TITLE
Create USB boot drive with Ubuntu and ROS installed

### ISSUE THREAD

**Issue by NickGans** [UTDallas-SeRViCELab/Cyton-Arm-ROS-Labs#1]
<This is mostly a test of the project management, as I am not yet familiar with it.  So please indulge me with some project correspondence.> 

Ubuntu will not boot off of a thumb drive on a Windows 10 machine

**Comment by mclkarnes** [comment]
Solution:
Boot Ubuntu from thumb drive on Windows 7 machines in lab
